version: '3.8'

services:
  mongo:
    image: mongo:latest  # Use a specific version tag like mongo:4.4, if needed
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express  # Use a specific version tag like mongo-express:0.54, if needed
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/
